version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "1000:1000" 
    depends_on:
      - db
volumes:
  postgres_data:

